### ISSUE TITLE
Unable to install plugin via phonegap build

### ISSUE THREAD

**Issue by bx67212** [artemisoftnian/com-artemisoftnian-plugins-unityads2#1]
When I try to build a basic project I receive this error from phonegap build:

> Error - Plugin error (you probably need to remove plugin files from your app): //github.com/artemisoftnian/com-artemisoftnian-plugins-unityads2 --nohooks=.": Fetching plugin "https://github.com/artemisoftnian/com-artemisoftnian-plugins-unityads2" via git clone Using shallow clone Repository "https://github.com/artemisoftnian/com-artemisoftnian-plugins-unityads2" checked out to git ref "master" at "9dcbff3". Installing "com-artemisoftnian-plugins-unityads2" at "0.0.1" for android Error during processing of action! Attempting to revert... Failed to install 'com-artemisoftnian-plugins-unityads2': CordovaError: Uh oh! Destination "/libs/classes.jar" for source file "/tmp/gimlet/12798280/3150099/www_android/project/cordova/plugins/com-artemisoftnian-plugins-unityads2/src/android/libs/classes.jar" is located outside the project at copyFile (/tmp/gimlet/12798280/3150099/www_android/project/cordova/lib/pluginHandlers.js:231:15) at install (/tmp/gimlet/12798280/3150099/www_android/project/cordova/lib/pluginHandlers.js:74:13) at Object.process (/tmp/gimlet/12798280/3150099/www_android/project/cordova/node_modules/cordova-common/src/ActionStack.js:56:25) at PluginManager.doOperation (/tmp/gimlet/12798280/3150099/www_android/project/cordova/node_modules/cordova-common/src/PluginManager.js:117:20) at PluginManager.addPlugin (/tmp/gimlet/12798280/3150099/www_android/project/cordova/node_modules/cordova-common/src/PluginManager.js:147:17) at /tmp/gimlet/12798280/3150099/www_android/project/cordova/Api.js:254:18 at _fulfilled (/tmp/gimlet/12798280/3150099/www_android/project/cordova/node_modules/q/q.js:834:54) at self.promiseDispatch.done (/tmp/gimlet/12798280/3150099/www_android/project/cordova/node_modules/q/q.js:863:30) at Promise.promise.promiseDispatch (/tmp/gimlet/12798280/3150099/www_android/project/cordova/node_modules/q/q.js:796:13) at /tmp/gimlet/12798280/3150099/www_android/project/cordova/node_modules/q/q.js:556:49 Uh oh! Destination "/libs/classes.jar" for source file "/tmp/gimlet/12798280/3150099/www_android/project/cordova/plugins/com-artemisoftnian-plugins-unityads2/src/android/libs/classes.jar" is located outside the project

In my config file I insert:

`<plugin name="com-artemisoftnian-plugins-unityads2" source="npm"/>`

**Comment by creakosta** [comment]
I have build fail too via Phonegap Build

**Comment by bx67212** [comment]
I think there is no solution so I close
