### ISSUE TITLE
requireCordovaModule is not supported

### ISSUE THREAD

**Issue by hesamr76** [artemisoftnian/com-artemisoftnian-plugins-unityads2#4]
Using "requireCordovaModule" to load non-cordova module "q" is not supported.

In afterPrepareScript.js file.

Replace the requireCordovaModule to require :
line 5: ctx.requireCordovaModule("q") to require("q")

thanks

**Comment by artemisoftnian** [comment]
Fix!,  Thanks for pointing it out!   Although the next version its already finish but still not publish yet!.  This Project will be marked as depreciated soon!
